import { Product, Supplier, Course } from "./types";

export const COLOR_SEASONS = [
  "浅春",
  "暖春",
  "净春",
  "柔夏",
  "冷夏",
  "深夏",
  "柔秋",
  "暖秋",
  "净秋",
  "深秋",
  "净冬",
  "冷冬",
] as const;

export const STYLE_TYPES = [
  "淑女风",
  "知性风",
  "名媛风",
  "中性风",
  "潮牌风",
  "职业风",
  "休闲风",
  "大牌风",
] as const;

export const COLOR_SEASON_COLORS: Record<string, string> = {
  浅春: "#F9A8D4",
  暖春: "#FB923C",
  净春: "#FDE047",
  柔夏: "#A5B4FC",
  冷夏: "#818CF8",
  深夏: "#6366F1",
  柔秋: "#D4A574",
  暖秋: "#C2855A",
  净秋: "#E8B931",
  深秋: "#92400E",
  净冬: "#E0E7FF",
  冷冬: "#1E3A5F",
};

export const products: Product[] = [
  {
    id: "p001",
    name: "法式方领碎花连衣裙",
    images: ["/images/product-placeholder.svg"],
    color_season: "浅春",
    style_type: "浪漫型",
    stock: 156,
    wholesale_price: 128,
    retail_price: 399,
    attributes: {
      fabric: "雪纺",
      season: "春夏",
      occasion: "日常/约会",
      fit: "修身",
      sizes: ["S", "M", "L", "XL"],
    },
    description:
      "法式方领设计，展现锁骨线条；飘逸雪纺面料搭配小碎花印花，浪漫优雅。高腰A字裙摆，修饰身形比例。",
    supplier_id: "s001",
    is_hot: true,
  },
  {
    id: "p002",
    name: "经典黑色西装外套",
    images: ["/images/product-placeholder.svg"],
    color_season: "冷冬",
    style_type: "古典型",
    stock: 89,
    wholesale_price: 235,
    retail_price: 699,
    attributes: {
      fabric: "精纺羊毛混纺",
      season: "秋冬",
      occasion: "商务/通勤",
      fit: "合身",
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    description:
      "经典版型西装外套，精纺羊毛混纺面料挺括有型。垫肩设计修饰肩线，双扣闭合简约大方，职场必备单品。",
    supplier_id: "s002",
    is_hot: true,
  },
  {
    id: "p003",
    name: "少女感蓬蓬半裙",
    images: ["/images/product-placeholder.svg"],
    color_season: "净春",
    style_type: "少女型",
    stock: 42,
    wholesale_price: 89,
    retail_price: 299,
    attributes: {
      fabric: "网纱+缎面内衬",
      season: "春夏",
      occasion: "约会/派对",
      fit: "高腰A字",
      sizes: ["XS", "S", "M", "L"],
    },
    description:
      "多层网纱蓬蓬裙摆，内衬缎面顺滑舒适。高腰设计拉长腿部比例，搭配简约上衣即可打造淑女风感。",
    supplier_id: "s003",
    is_hot: false,
  },
  {
    id: "p004",
    name: "优雅驼色羊绒大衣",
    images: ["/images/product-placeholder.svg"],
    color_season: "暖秋",
    style_type: "优雅型",
    stock: 0,
    wholesale_price: 458,
    retail_price: 1299,
    attributes: {
      fabric: "双面羊绒",
      season: "秋冬",
      occasion: "商务/日常",
      fit: "宽松",
      sizes: ["S", "M", "L", "XL"],
    },
    description:
      "甄选双面羊绒面料，手感柔软亲肤。驼色经典不过时，宽松落肩设计兼顾保暖与优雅，系带穿法更显腰线。",
    supplier_id: "s004",
    is_hot: true,
  },
  {
    id: "p005",
    name: "时尚撞色拼接卫衣",
    images: ["/images/product-placeholder.svg"],
    color_season: "深夏",
    style_type: "时尚型",
    stock: 210,
    wholesale_price: 68,
    retail_price: 239,
    attributes: {
      fabric: "加厚棉质毛圈",
      season: "春秋",
      occasion: "休闲/街头",
      fit: "oversize",
      sizes: ["M", "L", "XL", "XXL"],
    },
    description:
      "大胆撞色拼接设计，打破沉闷增添时尚感。加厚毛圈面料舒适保暖，oversize版型慵懒随性，街头潮流必备。",
    supplier_id: "s005",
    is_hot: false,
  },
  {
    id: "p006",
    name: "自然风棉麻阔腿裤",
    images: ["/images/product-placeholder.svg"],
    color_season: "柔秋",
    style_type: "自然型",
    stock: 15,
    wholesale_price: 95,
    retail_price: 329,
    attributes: {
      fabric: "棉麻混纺",
      season: "春夏秋",
      occasion: "日常/度假",
      fit: "宽松直筒",
      sizes: ["S", "M", "L", "XL"],
    },
    description:
      "天然棉麻面料，透气舒适亲肤。高腰阔腿设计拉长腿部线条，松紧腰头穿脱方便，尽显自然随性风格。",
    supplier_id: "s006",
    is_hot: false,
  },
  {
    id: "p007",
    name: "戏剧感夸张袖衬衫",
    images: ["/images/product-placeholder.svg"],
    color_season: "净冬",
    style_type: "戏剧型",
    stock: 67,
    wholesale_price: 145,
    retail_price: 459,
    attributes: {
      fabric: "真丝缎面",
      season: "四季",
      occasion: "晚宴/活动",
      fit: "修身",
      sizes: ["XS", "S", "M", "L"],
    },
    description:
      "真丝缎面面料光泽感十足，夸张灯笼袖设计极具戏剧张力。前襟暗扣设计简洁大气，搭配高腰裤尽显气场。",
    supplier_id: "s007",
    is_hot: true,
  },
  {
    id: "p008",
    name: "少年风短款皮夹克",
    images: ["/images/product-placeholder.svg"],
    color_season: "深秋",
    style_type: "少年型",
    stock: 33,
    wholesale_price: 320,
    retail_price: 899,
    attributes: {
      fabric: "绵羊皮",
      season: "秋冬",
      occasion: "日常/机车",
      fit: "短款修身",
      sizes: ["S", "M", "L"],
    },
    description:
      "头层绵羊皮柔软细腻，短款修身剪裁利落有型。拉链装饰增添硬朗气质，搭配牛仔裤或裙装皆可帅气出街。",
    supplier_id: "s002",
    is_hot: false,
  },
  {
    id: "p009",
    name: "浪漫蕾丝拼接长裙",
    images: ["/images/product-placeholder.svg"],
    color_season: "暖春",
    style_type: "浪漫型",
    stock: 78,
    wholesale_price: 168,
    retail_price: 529,
    attributes: {
      fabric: "蕾丝+雪纺",
      season: "春夏",
      occasion: "婚礼/晚宴",
      fit: "收腰A字",
      sizes: ["S", "M", "L", "XL"],
    },
    description:
      "精致蕾丝上身拼接飘逸雪纺裙摆，收腰设计勾勒优美曲线。若隐若现的蕾丝花纹浪漫迷人，适合各种正式场合。",
    supplier_id: "s001",
    is_hot: true,
  },
  {
    id: "p010",
    name: "古典型格纹西装套装",
    images: ["/images/product-placeholder.svg"],
    color_season: "冷夏",
    style_type: "古典型",
    stock: 52,
    wholesale_price: 388,
    retail_price: 1099,
    attributes: {
      fabric: "毛涤混纺",
      season: "秋冬",
      occasion: "商务/会议",
      fit: "合身",
      sizes: ["S", "M", "L", "XL"],
    },
    description:
      "经典千鸟格格纹，毛涤混纺面料挺括抗皱。西装+西裤成套搭配，干练不失优雅，职场女性的品质之选。",
    supplier_id: "s004",
    is_hot: false,
  },
  {
    id: "p011",
    name: "优雅真丝印花衬衫",
    images: ["/images/product-placeholder.svg"],
    color_season: "柔夏",
    style_type: "优雅型",
    stock: 124,
    wholesale_price: 198,
    retail_price: 599,
    attributes: {
      fabric: "桑蚕丝",
      season: "春夏",
      occasion: "商务/日常",
      fit: "微宽松",
      sizes: ["S", "M", "L", "XL"],
    },
    description:
      "100%桑蚕丝面料，亲肤透气有光泽。手工卷边细节考究，淡雅印花尽显优雅品味，职场与日常皆宜。",
    supplier_id: "s003",
    is_hot: false,
  },
  {
    id: "p012",
    name: "时尚型解构风风衣",
    images: ["/images/product-placeholder.svg"],
    color_season: "净秋",
    style_type: "时尚型",
    stock: 8,
    wholesale_price: 275,
    retail_price: 799,
    attributes: {
      fabric: "防水涂层风衣布",
      season: "春秋",
      occasion: "通勤/街拍",
      fit: "不规则",
      sizes: ["S", "M", "L"],
    },
    description:
      "解构主义设计，不对称下摆与可拆卸袖带彰显个性。防水涂层面料实用防风，时尚与功能兼具的前沿单品。",
    supplier_id: "s005",
    is_hot: true,
  },
];

export const suppliers: Supplier[] = [
  {
    id: "s001",
    company_name: "杭州锦丝服饰有限公司",
    contact_person: "张丽华",
    phone: "0571-88234567",
    main_categories: ["连衣裙", "衬衫", "半裙"],
    brand: "锦丝印象",
    annual_capacity: "50万件",
    rating: 4.8,
    level: "A",
    status: "活跃",
    created_at: "2024-01-15",
  },
  {
    id: "s002",
    company_name: "广州皮匠世家贸易有限公司",
    contact_person: "李建国",
    phone: "020-87654321",
    main_categories: ["皮衣", "皮裤", "皮裙"],
    brand: "匠皮",
    annual_capacity: "20万件",
    rating: 4.6,
    level: "A",
    status: "活跃",
    created_at: "2024-02-20",
  },
  {
    id: "s003",
    company_name: "深圳柔缎时装有限公司",
    contact_person: "王美琳",
    phone: "0755-22334455",
    main_categories: ["真丝衬衫", "丝绸连衣裙"],
    brand: "柔缎",
    annual_capacity: "30万件",
    rating: 4.5,
    level: "A",
    status: "活跃",
    created_at: "2024-03-10",
  },
  {
    id: "s004",
    company_name: "大连北方毛纺集团有限公司",
    contact_person: "赵铁柱",
    phone: "0411-67890123",
    main_categories: ["大衣", "西装", "套装"],
    brand: "北毛",
    annual_capacity: "80万件",
    rating: 4.7,
    level: "A",
    status: "活跃",
    created_at: "2024-01-08",
  },
  {
    id: "s005",
    company_name: "东莞潮派服饰有限公司",
    contact_person: "陈晓东",
    phone: "0769-11223344",
    main_categories: ["卫衣", "风衣", "外套"],
    brand: "潮派",
    annual_capacity: "100万件",
    rating: 4.2,
    level: "B",
    status: "活跃",
    created_at: "2024-04-15",
  },
  {
    id: "s006",
    company_name: "南通棉语纺织科技有限公司",
    contact_person: "刘芬",
    phone: "0513-55667788",
    main_categories: ["棉麻裤装", "休闲衬衫"],
    brand: "棉语",
    annual_capacity: "40万件",
    rating: 4.0,
    level: "B",
    status: "活跃",
    created_at: "2024-05-01",
  },
  {
    id: "s007",
    company_name: "上海缦织服饰设计有限公司",
    contact_person: "吴雅婷",
    phone: "021-99887766",
    main_categories: ["真丝衬衫", "晚装", "礼服"],
    brand: "缦织",
    annual_capacity: "15万件",
    rating: 4.9,
    level: "B",
    status: "活跃",
    created_at: "2024-03-22",
  },
  {
    id: "s008",
    company_name: "嘉兴新锐制衣厂",
    contact_person: "周小波",
    phone: "0573-33445566",
    main_categories: ["基础T恤", "休闲裤"],
    brand: "新锐",
    annual_capacity: "200万件",
    rating: 3.5,
    level: "C",
    status: "活跃",
    created_at: "2024-06-10",
  },
];

export const courses: Course[] = [
  {
    id: "c001",
    title: "色彩季型诊断入门课",
    price: 199,
    level: "入门",
    description:
      "从零开始了解个人色彩季型理论，掌握12季色彩体系基础，学会辨别自己的色彩季型。",
    outline: [
      "色彩基础理论与色彩三属性",
      "12季色彩体系总览",
      "暖色与冷色的辨识方法",
      "自我色彩季型初步判断",
      "日常穿搭色彩搭配入门",
    ],
    created_at: "2024-01-01",
  },
  {
    id: "c002",
    title: "色彩风格进阶实战课",
    price: 9999,
    level: "进阶",
    description:
      "深入掌握12季色彩体系与8大风格类型，学会为不同人群制定精准的穿搭方案。",
    outline: [
      "12季色彩体系深度解析",
      "8大风格类型精准判定",
      "色彩+风格综合搭配方案",
      "客户诊断实操演练",
      "季节性选品与陈列色彩规划",
    ],
    created_at: "2024-02-01",
  },
  {
    id: "c003",
    title: "色彩顾问认证课程",
    price: 19800,
    level: "认证",
    description:
      "系统化专业培训，通过考核获得色彩顾问认证资质，可独立开展个人形象诊断业务。",
    outline: [
      "色彩理论体系全阶课程",
      "风格诊断与形象设计",
      "1对1实操诊断训练",
      "商业运营与客户管理",
      "认证考试与资质颁发",
    ],
    created_at: "2024-03-01",
  },
  {
    id: "c004",
    title: "品牌全案赋能课程",
    price: 39800,
    level: "全案",
    description:
      "面向服装品牌主理人和供应链管理者，从色彩企划到销售全链路赋能，实现数据驱动精准运营。",
    outline: [
      "品牌色彩战略规划",
      "供应链色彩管理体系",
      "门店陈列与视觉营销",
      "数据驱动选品与企划",
      "VIP客户运营与复购提升",
      "全案项目实战与答辩",
    ],
    created_at: "2024-04-01",
  },
];
