export default {
  pages: [
    'pages/home/index/index',
    'pages/courses/index/index',
    'pages/hot-picks/index/index',
    'pages/news/index/index',
    'pages/vip/index/index',
    'pages/courses/detail/index/index',
    'pages/hot-picks/detail/index/index',
    'pages/news/detail/index/index',
    'pages/vip/login/index/index',
    'pages/vip/register/index/index',
    'pages/vip/profile/index/index',
    'pages/vip/style-test/index/index',
    'pages/planning/index/index',
    'pages/buyer/index/index',
    'pages/category/index/index',
    'pages/collocation/index/index',
    'pages/contact/index/index',
    'pages/agent/recruit/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#2d1b2e',
    navigationBarTitleText: '骆芷蝶智选',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    custom: true,
    color: '#999999',
    selectedColor: '#1a1a2e',
    borderStyle: 'white',
    backgroundColor: '#ffffff',
    list: [
      { pagePath: 'pages/home/index/index', text: '首页', iconPath: 'assets/tabbar/home.png', selectedIconPath: 'assets/tabbar/home-active.png' },
      { pagePath: 'pages/category/index/index', text: '分类', iconPath: 'assets/tabbar/plan.png', selectedIconPath: 'assets/tabbar/plan-active.png' },
      { pagePath: 'pages/buyer/index/index', text: '购物车', iconPath: 'assets/tabbar/stock.png', selectedIconPath: 'assets/tabbar/stock-active.png' },
      { pagePath: 'pages/vip/index/index', text: '会员', iconPath: 'assets/tabbar/vip.png', selectedIconPath: 'assets/tabbar/vip-active.png' },
      { pagePath: 'pages/vip/profile/index/index', text: '我的', iconPath: 'assets/tabbar/user.png', selectedIconPath: 'assets/tabbar/user-active.png' },
    ],
  },
}
